// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHISThIJWx4W8svYx9YkiUPBTttvieasY',
    appId: '1:627185019923:web:d4f8d8115b40b78341a3e6',
    messagingSenderId: '627185019923',
    projectId: 'filinvest-bank-group',
    authDomain: 'filinvest-bank-group.firebaseapp.com',
    storageBucket: 'filinvest-bank-group.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJg-wdqkMy9ovc8QTfFZwgt00XrJqPBoI',
    appId: '1:627185019923:android:780e1f8b2c46267b41a3e6',
    messagingSenderId: '627185019923',
    projectId: 'filinvest-bank-group',
    storageBucket: 'filinvest-bank-group.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvWiQgC22rjLpDPxuq4ZIWDdJr6Bn86Wc',
    appId: '1:627185019923:ios:c5cddcf942811c2f41a3e6',
    messagingSenderId: '627185019923',
    projectId: 'filinvest-bank-group',
    storageBucket: 'filinvest-bank-group.firebasestorage.app',
    iosBundleId: 'com.example.filinvestBank',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvWiQgC22rjLpDPxuq4ZIWDdJr6Bn86Wc',
    appId: '1:627185019923:ios:c5cddcf942811c2f41a3e6',
    messagingSenderId: '627185019923',
    projectId: 'filinvest-bank-group',
    storageBucket: 'filinvest-bank-group.firebasestorage.app',
    iosBundleId: 'com.example.filinvestBank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHISThIJWx4W8svYx9YkiUPBTttvieasY',
    appId: '1:627185019923:web:22c42656f6a6107d41a3e6',
    messagingSenderId: '627185019923',
    projectId: 'filinvest-bank-group',
    authDomain: 'filinvest-bank-group.firebaseapp.com',
    storageBucket: 'filinvest-bank-group.firebasestorage.app',
  );
}
